ALTER TABLE authors
    ADD COLUMN IF NOT EXISTS bic VARCHAR(20) NOT NULL DEFAULT '' AFTER bank_account,
    ADD COLUMN IF NOT EXISTS bank_name VARCHAR(255) NOT NULL DEFAULT '' AFTER bic,
    ADD COLUMN IF NOT EXISTS paypal_address VARCHAR(255) NOT NULL DEFAULT '' AFTER bank_name;
